services:
  - type: web
    name: crop-fertilizer-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install setuptools==68.2.2 wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
